In [1]:
#importing libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# import seaborn as sns
# get_ipython().run_line_magic('matplotlib', 'inline')
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier



In [2]:

#reading the dataset
dataset = pd.read_csv("dataset/maindataset.csv", index_col=0)

dataset.head()


Database  C++  Analytical Skills  Python  C  Java  Csharp  R  Statistics  \
1         7    1                  8      10  1     1       3  2           7   
2         7    2                  8       9  2     2       0  6           6   
3         7    3                  8       9  3     9       2  9          10   
4         8    0                  6       7  0     2       0  8          10   
5         8    1                  7       8  1     4       1  7           9   

   CSS  ...  Php  Javascript  Algorithm  Cyber Security  OS  Psyocology  SQL  \
1    0  ...    0           0          9               0   0           6    8   
2    0  ...    0           0          9               0   0           6    8   
3    0  ...    0           0          9               0   0           6    8   
4    0  ...    0           1          9               3   5           1    7   
5    0  ...    0           2          9               2   3           1    7   

   Communication Skill  Software Testing                TARGET CLASS  
1                    5                 5     Artificial intelligence  
2                    5                 6     Artificial intelligence  
3                    5                 7     Artificial intelligence  
4                    6                 7  data science and analytics  
5                    6                 7  data science and analytics  

[5 rows x 21 columns]

In [12]:
# parameters considered

print(len(dataset.columns)-1)
dataset.columns


20


Index(['Database', 'C++', 'Analytical Skills', 'Python', 'C', 'Java', 'Csharp',
       'R', 'Statistics', 'CSS', 'Html', 'Php', 'Javascript', 'Algorithm',
       'Cyber Security', 'OS', 'Psyocology', 'SQL', 'Communication Skill',
       'Software Testing', 'TARGET CLASS'],
      dtype='object')

In [14]:
#courses that will be recommended

courses_name=list(dataset['TARGET CLASS'].drop_duplicates())

print(len(courses_name))

courses_name

18


['Artificial intelligence',
 'data science and analytics',
 'machine learning',
 'robotics',
 'human computer interaction',
 'management information system',
 'applied research and innovation',
 'network management',
 'cloud computing',
 'operation research',
 'enterprise architecture management',
 'software engineering',
 'cyber security',
 'computer vision',
 'videogame programming',
 'distributed system an web technology',
 'web design and development',
 'computer science']

In [15]:
# division of dataset into features and target class

X=dataset.iloc[:, :-1].values
y=dataset.iloc[:, -1].values


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [20]:
# apply knn algorithm

classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)
#predict for x_test
y_pred = classifier.predict(X_test)


In [24]:
distances, indices = classifier.kneighbors(X[[0]],  n_neighbors=2)

print(distances, indices)
print(X[104])
print(X[237])

[[0.         5.56776436]] [[104 237]]
[6 3 4 3 4 5 4 3 6 5 4 4 4 5 9 7 1 7 5 8]
[6 3 4 3 3 5 1 2 1 9 9 8 8 2 8 6 0 9 8 7]
